In [4]:
import numpy as np

In [6]:
#ARRAY

#LIST
#Mengubah LIST 1-d menjadi array 1-d (VECTOR)
a = np.array([1,2,3,4,5])
print(f'a = {a}')
b = np.array([1.5,2.5,5,6,7])
print(f'b = {b}')
#Mengubah LIST 2-d menjadi array 2-d (MATRICS)
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'a2 = {a2}')

print()

#TUPLE
#Mengubah TUPLE 1-d menjadi array 1-d (VECTOR)
a1 = np.array((1,2,3,4,5))
print(f'a1 = {a1}')
b1 = np.array((1.5,2.5,5,6,7))
print(f'b1 = {b1}')
#Mengubah TUPLE 2-d menjadi array 2-d (MATRICS)
b2 = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(f'b2 = {b2}')

a = [1 2 3 4 5]
b = [1.5 2.5 5.  6.  7. ]
a2 = [[1 2 3]
 [4 5 6]
 [7 8 9]]

a1 = [1 2 3 4 5]
b1 = [1.5 2.5 5.  6.  7. ]
b2 = [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#ARANGE
#Membuat Array Vector dengan Range

# Membuat sebuah array vector  0 - 9
c = np.arange(10)
print(f'c : {c}')
# Membuat sebuah array vector  1- 10
d = np.arange(1,11)
print(f'd : {d}')
# Membuat sebuah array vector  0- 10 genap
e = np.arange(0,11,2)
print(f'e : {e}')
# Membuat sebuah array vector  10-0
f = np.arange(10,0,-1)
print(f'f : {f}')

c : [0 1 2 3 4 5 6 7 8 9]
d : [ 1  2  3  4  5  6  7  8  9 10]
e : [ 0  2  4  6  8 10]
f : [10  9  8  7  6  5  4  3  2  1]


In [45]:
#LINSPACE
#Membuat panjang array yg ditentukan (angka ketiga dari syntax), dengan jarak antar nilai pada array adalah sama

# Dari 1 - 10, sebanyak 4 angka
g = np.linspace(1,10,4)
print(f'g : {g}')
# Dari 0 - 10, sebanyak 2 angka
h = np.linspace(0,10,2)
print(f'h : {h}')
# Dari 0 - 10, sebanyak 5 angka
i = np.linspace(0,10,5)
print(f'i : {i}')
# Dari 1 - 10, sebanyak 10 angka
j = np.linspace(1,10,10)
print(f'j : {j}')

g : [ 1.  4.  7. 10.]
h : [ 0. 10.]
i : [ 0.   2.5  5.   7.5 10. ]
j : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
#RANDOM INTEGER

# Random integer dari 1 - 10, sebanyak 1 data
randInt = np.random.randint(1, 11) #--> (1,11) adalah arange dari 1-10 & (1/default/tidak ditampilak) adalah banyak data int yg ingin ditampilkan
print(f'randInt = {randInt}')
# Random integer dari 1 - 10, sebanyak 7 data
randInt2  = np.random.randint(1,11,7) #--> (1,11) adalah arange dari 1-10 & (7) adalah banyak data int yg ingin ditampilkan
print(f'randInt2 = {randInt2}')

randInt = 8
randInt2 = [1 4 7 3 8 7 8]


In [12]:
#SHAPE & RESHAPE

# shape digunakan untuk melihat  bentuk array
k = np.arange(1,7)
print(f'Array k : {k}')
print(f'shape k : {k.shape}')

print()

# reshape digunakan untuk mengubah bentu array
# reshape(2, 3) --> Mengubah bentuk menjadi 2 baris 3 kolom
k1 = k.reshape(2, 3)
print(f'reshape k(2 baris,3 kolom) :\n {k1}')
print(f'shapenya : {k.reshape(2,3).shape}')
print()
# reshape(3, 2) --> Mengubah bentuk menjadi 3 baris 2 kolom
k2 = k.reshape(3, 2)
print(f'reshape k(3 baris,2 kolom) :\n {k2}')
print(f'shapenya : {k.reshape(3,2).shape}')
print()
# reshape(3, 2) --> Mengubah bentuk 3 baris 2 kolom, menjadi 1 baris
k3 = k2.reshape(6)
print(f'reshape k(3,2) mejadi 1 baris kembali : {k3}')
print(f'shapenya : {k.reshape(6).shape}')


Array k : [1 2 3 4 5 6]
shape k : (6,)

reshape k(2 baris,3 kolom) :
 [[1 2 3]
 [4 5 6]]
shapenya : (2, 3)

reshape k(3 baris,2 kolom) :
 [[1 2]
 [3 4]
 [5 6]]
shapenya : (3, 2)

reshape k(3,2) mejadi 1 baris kembali : [1 2 3 4 5 6]
shapenya : (6,)


In [76]:
#MAX() & MIN()

# Random dari 0 - 49, sebanyak 10 data
rndmArr = np.random.randint(0,50,10)
print(rndmArr)

maxInt = rndmArr.max()
print(f'nilai max dari random array : {maxInt}')
print(f'cara ke-2 dengan universal function = {np.max(maxInt)}') #syntax menggunakan universal function
minInt = rndmArr.min()
print(f'nilai min dari random array : {minInt}')

[29 45 43 39 28 12  6 23 27 17]
nilai max dari random array : 45
cara ke-2 dengan universal function = 45
nilai min dari random array : 6


In [81]:
#MAX & MIN pada Array 2-d / MATRICS

vctr = np.arange(1,26)
print(f'Vector :\n {vctr}')
#reshape vector menjadi matrics (5,5)
mtrx = vctr.reshape(5,5)
print(f'Matrics (5,5):\n {mtrx}')

#Mencari nilai MAX & MIN dari matrics
maxMtrx = mtrx.max()
print(f'Nilai Max dari Matrics (5,5) : {maxMtrx}')
minMtrx = mtrx.min()
print(f'Nilai Min dari Matrics (5,5) : {minMtrx}')
print()

#Mencari nilai MAX & MIN baris ke 2&5 pada matrics

#ambil baris yang ingin dicari nilai Max & Min nya
print('Matrics baris 2&5 :')
print(mtrx[1])
print(mtrx[-1])
print()
print(f'Nilai Max pada baris ke-2 : {mtrx[1].max()}')
print(f'Nilai Min pada baris ke-4 (baris terakhir) : {mtrx[-1].min()}')




Vector :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Matrics (5,5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Nilai Max dari Matrics (5,5) : 25
Nilai Min dari Matrics (5,5) : 1

Matrics baris 2&5 :
[ 6  7  8  9 10]
[21 22 23 24 25]

Nilai Max pada baris ke-2 : 10
Nilai Min pada baris ke-4 (baris terakhir) : 21


In [62]:
#INDEXING

#INDEXING ONE DIMENSION
print('INDEXING ONE DIMENSION')
arrRange = np.arange(0,11)
print(f'arrRange = {arrRange}')
#Indeks 4 dari arrRange
print(f'Indek ke-4 arrRange : {arrRange[4]}')
# Select dari index 2 - 6 arrRange
print(f'indeks 2-6 arrRange : {arrRange[2:7]}')
# Select dari index awal - 6
print(f'indeks pertama-6 arrRange : {arrRange[:7]}')
# Select dari index 2 - selesai
print(f'indeks ke 2-terakhir arrRange : {arrRange[2:]}')
print()

#BROADCASTING

arrRange[2:7] = 99 #menngganti angka pada indeks 2-6 menjadi angka 99
print(f'broadcast : {arrRange}')
print()


#INDEXING TWO DIMENSION
print('INDEXING TWO DIMENSION')
arrMatrics = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arrMatrics)
#indeks ke-1 pada arrMatrics
print(f'indeks 1 arrMatrics : {arrMatrics[1]}')

# Access value
print('Value pada indeks 1 dari indeks 1 matrics arrMatrics :')
print(arrMatrics[1][1])
# or
print(arrMatrics[1, 1])

#index pertama-kedua 
print(f'index pertama-kedua arrMatrics :\n {arrMatrics[0:2]}')
print()
# row : 2 (index 0 - 1)
# column 1: (index 1 - terakhir)
print('nilai pada baris pertama-kedua & kolom kedua-terkahir :')
print(arrMatrics[: 2, 1 :])

# row : index 1 - selesai
# column : index 0 - 1
print('nilai pada baris kedua-terakhir & kolom pertama-kedua :')
print(arrMatrics[1:, 0 :2])



INDEXING ONE DIMENSION
arrRange = [ 0  1  2  3  4  5  6  7  8  9 10]
Indek ke-4 arrRange : 4
indeks 2-6 arrRange : [2 3 4 5 6]
indeks pertama-6 arrRange : [0 1 2 3 4 5 6]
indeks ke 2-terakhir arrRange : [ 2  3  4  5  6  7  8  9 10]

broadcast : [ 0  1 99 99 99 99 99  7  8  9 10]

INDEXING TWO DIMENSION
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
indeks 1 arrMatrics : [20 25 30]
Value pada indeks 1 dari indeks 1 matrics arrMatrics :
25
25
index pertama-kedua arrMatrics :
 [[ 5 10 15]
 [20 25 30]]

nilai pada baris pertama-kedua & kolom kedua-terkahir :
[[10 15]
 [25 30]]
nilai pada baris kedua-terakhir & kolom pertama-kedua :
[[20 25]
 [35 40]]


In [71]:
#SELCETION
arrInt = np.arange(1, 11)
print(arrInt)
print()

#menampilkan nilai boolean jika nilai pada aray arrInt lebih dari 5
arrBool = arrInt > 5
print(arrBool)
#mengambil nilai pada array arrInt yang lebih besar dari 5
print(arrInt[arrInt > 5])
#mengambil nilai pada array arrInt yang habis dibagi 2
print(arrInt[arrInt % 2 == 0])
#menambahkan nilai pada array arrInt dengan 10
print(arrInt + 10)
#nilai modulus 2 pada setiap nilai di array arrInt
print(arrInt % 2)
#menambahkan nilai pada array arrInt dengan dirinya sendiri
print(arrInt + arrInt)
#mengkalikan nilai pada array arrInt dengan dirinya sendiri
print(arrInt * arrInt)

[ 1  2  3  4  5  6  7  8  9 10]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[11 12 13 14 15 16 17 18 19 20]
[1 0 1 0 1 0 1 0 1 0]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]


In [72]:
#UNIVERSAL FUNCTION

lstNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tupNumbers = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
# numbers = np.array(numbers)
print('Nilai max dari list : ',np.max(lstNumbers))
print('Nilai max dari tupple : ',np.max(tupNumbers))

Nilai max dari list :  10
Nilai max dari tupple :  10


In [87]:
#ZERO & ONE

#Zero Vector / 1-d
arrZero = np.zeros(5)
print(f'1-d : \n {arrZero}')
arrZero = np.zeros((5,5))
print(f'2-d : \n {arrZero}')

print()
arrOne = np.ones(5)
print(f'1-d : \n {arrOne}')
arrOne = np.ones((5,5))
print(f'2-d : \n {arrOne}')

1-d : 
 [0. 0. 0. 0. 0.]
2-d : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

1-d : 
 [1. 1. 1. 1. 1.]
2-d : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
