# Array

 > 1D - VECTOR

In [2]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:

print('Atau')
a = np.array([1,2,3,4,5])
print(a)

Atau
[1 2 3 4 5]


In [26]:
#float
np.array([1.5,2,3,4.7,5])

array([1.5, 2. , 3. , 4.7, 5. ])

> 2D - MATRIX

In [30]:
np.array(((1,2,3,4,5),(6,7,8,9,10))) #array dari tuple

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.array([[1,2,3,4,5,],[6,7,8,9,10]]) #array dari list

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
#float
np.array([[1,2,3.5,4,5.1],[6.2,7,8,9.6,10]])

array([[ 1. ,  2. ,  3.5,  4. ,  5.1],
       [ 6.2,  7. ,  8. ,  9.6, 10. ]])

> > Range / arange


In [15]:
#membuat vector dengan range

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

>> linspace

In [18]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [20]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

# Array 2-d /Matrix

In [22]:
np.array(((1,2,3,4,5),(6,7,8,9,10))) #array dari tuple

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.array([[1,2,3,4,5,],[6,7,8,9,10]]) #array dari list

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
#float
np.array([[1,2,3.5,4,5.1],[6.2,7,8,9.6,10]])

array([[ 1. ,  2. ,  3.5,  4. ,  5.1],
       [ 6.2,  7. ,  8. ,  9.6, 10. ]])

>> Zeores

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

>> Identity / Eye

In [50]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])