In [1]:
import numpy as np

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[9,10,11]])
print(a)
print(f'Matriks a memiliki bentuk : {a.shape}')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]
Matriks a memiliki bentuk : (4, 3)


>Transpose Matriks
 - mereturn sebuah bentuk matriks baru(menukar baris dan kolom), tp tidak mengubah bentuk asli matriks itu sendiri

In [13]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [14]:
print('Transpose Matriks a :')
print(a.transpose())
print(f'Matriks a memiliki bentuk : {a.shape}') #walaupun bentuknya menjadi (3,4) tp bentuk aslinya tetap (4,3)

Transpose Matriks a :
[[ 1  4  7  9]
 [ 2  5  8 10]
 [ 3  6  9 11]]
Matriks a memiliki bentuk : (4, 3)


>Flatten Array, Vector Basis

In [11]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [12]:
print('Flatten Matriks a :')
print(a.ravel())
print(f'Matriks a memiliki bentuk : {a.shape}') #walaupun bentuknya menjadi (3,4) tp bentuk aslinya tetap (4,3)

Flatten Matriks a :
[ 1  2  3  4  5  6  7  8  9  9 10 11]
Matriks a memiliki bentuk : (4, 3)


>Reshape

In [15]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [16]:
print('Reshape Matriks a :')
print(a.reshape(2,6))
print(f'Matriks a memiliki bentuk : {a.shape}') #walaupun bentuknya menjadi (3,4) tp bentuk aslinya tetap (4,3)

Reshape Matriks a :
[[ 1  2  3  4  5  6]
 [ 7  8  9  9 10 11]]
Matriks a memiliki bentuk : (4, 3)


>Resize

In [18]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [21]:
print('Resize Matriks a :')
print(a.resize(2,6)) #tidak mengembalikan nilai. karena fungsi resize merubah bentuk matriks secara permanen. syntaxnya harus dirubah
print(f'Matriks a memiliki bentuk : {a.shape}') #merubah bentuk matriks menjadi dari (4,3) menjadi (2,6)

Resize Matriks a :
None
Matriks a memiliki bentuk : (2, 6)


In [24]:
#agar resize mengembalikan sebuah nilai maka,
a.resize(2,6)
print(a)
print(f'Matriks a memiliki bentuk : {a.shape}') #merubah bentuk matriks menjadi dari (4,3) menjadi (2,6)

[[ 1  2  3  4  5  6]
 [ 7  8  9  9 10 11]]
Matriks a memiliki bentuk : (2, 6)
