In [1]:
import numpy as np

In [2]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
a = np.arange(0,10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


> Mengambil Nilai

In [17]:
#Menggunakan index, sama seperti pada python

print(f'Elemen ke-1 dari a adalah : {a[0]}')
print(f'Elemen ke-7 dari a adalah : {a[6]}')
print(f'Elemen ke-4 dari a adalah : {a[3]}')
print(f'Elemen terakhir dari a adalah : {a[-1]}')

Elemen ke-1 dari a adalah : 0
Elemen ke-7 dari a adalah : 36
Elemen ke-4 dari a adalah : 9
Elemen terakhir dari a adalah : 81


> Slicing

In [26]:
print(f'Elemen dari 1-6 : {a[0:6]}')
print(f'Elemen dari 4-akhir : {a[3:]}')
print(f'Elemen dari awal-5 : {a[0:5]}')
print(f'Elemen dari 3-8 : {a[2:8]}')

Elemen dari 1-6 : [ 0  1  4  9 16 25]
Elemen dari 4-akhir : [ 9 16 25 36 49 64 81]
Elemen dari awal-5 : [ 0  1  4  9 16]
Elemen dari 3-8 : [ 4  9 16 25 36 49]


> Iterasi / Loop

In [27]:
for i in a:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [38]:
even = []
odd = []
for i in range(len(a)):
    if a[i] % 2 == 0:
        even.append (a[i])
    else:
        odd.append (a[i]) 
print(a)        
print(even)
print(odd)
        
        
    

[ 0  1  4  9 16 25 36 49 64 81]
[0, 4, 16, 36, 64]
[1, 9, 25, 49, 81]
