Perkalian matriks bisa dioperasikan dengan kondisi :
- jumlah baris dan kolom pada kedua matriks sama
- jumlah kolom pada matriks pertama = jumlah baris pada matriks kedua

Perkalian matrik tidak dapat dioperasikan jika :
- jumlah baris dan kolom pada kedua matriks berbeda
- jumlah kolom pada matrik pertama TIDAK SAMA dengan jumlah baris pada matrik kedua

In [28]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.ones((3,3))

print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
mulMtrx = np.dot(a,b)
print(mulMtrx)

[[ 6.  6.  6.]
 [15. 15. 15.]]


In [10]:
#atau
mulMtrx2 = a.dot(b)
print(mulMtrx2)

[[ 6.  6.  6.]
 [15. 15. 15.]]


In [24]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
d = c*-1

print(c)
print()
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ -1  -2  -3  -4]
 [ -5  -6  -7  -8]
 [ -9 -10 -11 -12]
 [-13 -14 -15 -16]]


In [25]:
x = np.dot(c,d)
print(x)

[[ -90 -100 -110 -120]
 [-202 -228 -254 -280]
 [-314 -356 -398 -440]
 [-426 -484 -542 -600]]


In [35]:
#atau
print(c.dot(d))

[[ -90 -100 -110 -120]
 [-202 -228 -254 -280]
 [-314 -356 -398 -440]
 [-426 -484 -542 -600]]


In [61]:
#jumlah kolom pada matriks pertama = jumlah baris pada matriks kedua
#walaupun ukurannya bukan (4,3)-(3,4) atau (2,3)-(3,2) / walapun jumlah data pada kedua matriks berbeda

x = np.arange(1,13).reshape(4,3) #jumlah data 12
y = np.arange(1,7).reshape(3,2) #jumlah data 6
print(x)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2]
 [3 4]
 [5 6]]


In [62]:
res = np.dot(x,y)
print(res)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]]


In [50]:
#jumlah baris dan kolom pada kedua matriks sama / jumlah data pada kedua matriks sama
#jumlah kolom pada matriks pertama = jumlah baris pada matriks kedua


m = np.arange(1,13).reshape(2,6) #jumlah data 12
n = np.arange(13,25).reshape(6,2) #jumlah data 12
print(m)
print()
print(n)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


In [52]:
res = np.dot(m,n)
print(res)

[[ 413  434]
 [1061 1118]]


> Perkalian matriks yang tidak dapat dioperasikan

In [54]:
#Matriks ini tidak bisa dikalikan, karena  jumlah baris dan kolom pada kedua matriks berbeda
#jumlah p =7 & q=6. Tidak sama
#jumlah kolom pada matrik pertama TIDAK SAMA dengan jumlah baris pada matrik kedua

p = np.arange(1,13).reshape(4,3) #jumlah data 12
q = np.arange(1,9).reshape(2,4) #jumlah data 6
print(p)
print()
print(q)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
res = np.dot(p,q) #error

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [63]:
#matrik ini tidak dapat dikalikan, karena jumlah kolom pada matrik pertama TIDAK SAMA dengan jumlah baris pada matrik kedua
#walaupun jumlah data pada kedua mattiks sama

r = np.arange(1,13).reshape(4,3) #jumlah data 12
s = np.arange(13,25).reshape(2,6) #jumlah data 12
print(r)
print()
print(s)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [64]:
res = np.dot(r,s)

ValueError: shapes (4,3) and (2,6) not aligned: 3 (dim 1) != 2 (dim 0)