In [4]:
import numpy as np

In [14]:
#Element Wise

#Semua Operasi Aritmatika di array numpy merupakan elemen wise. BUKAN perkalian vector / matrix 'sesungguhnya'

> Array 1-d / Vector

In [2]:
np.array([1,2,3,4,5])+np.array([6,7,8,9,10])

array([ 7,  9, 11, 13, 15])

In [6]:
#atau
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a+b

array([ 7,  9, 11, 13, 15])

In [5]:
a-b

array([-5, -5, -5, -5, -5])

In [7]:
a*b

array([ 6, 14, 24, 36, 50])

In [8]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [25]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [26]:
a**b

array([      1,     128,    6561,  262144, 9765625], dtype=int32)

>Array 2-d / Matrix

In [18]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[7,8,9],[-1,-2,-3]])

c+d

array([[ 8, 10, 12],
       [ 3,  3,  3]])

In [19]:
c-d

array([[-6, -6, -6],
       [ 5,  7,  9]])

In [20]:
c*d

array([[  7,  16,  27],
       [ -4, -10, -18]])

In [21]:
c/d

array([[ 0.14285714,  0.25      ,  0.33333333],
       [-4.        , -2.5       , -2.        ]])

In [23]:
c**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [24]:
d**2

array([[49, 64, 81],
       [ 1,  4,  9]], dtype=int32)

In [27]:
d**c

array([[  7,  64, 729],
       [  1, -32, 729]], dtype=int32)