In [1]:
import numpy as np

In [23]:
#ARRAY

#LIST
#Mengubah LIST 1-d menjadi array 1-d (VECTOR)
a = np.array([1,2,3,4,5])
print(a)
b = np.array([1.5,2.5,5,6,7])
print(b)
#Mengubah LIST 2-d menjadi array 2-d (MATRICS)
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

print()

#TUPLE
#Mengubah TUPLE 1-d menjadi array 1-d (VECTOR)
a1 = np.array((1,2,3,4,5))
print(a1)
b1 = np.array((1.5,2.5,5,6,7))
print(b1)
#Mengubah TUPLE 2-d menjadi array 2-d (MATRICS)
b2 = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(b2)

[1 2 3 4 5]
[1.5 2.5 5.  6.  7. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5]
[1.5 2.5 5.  6.  7. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#ARANGE
#Membuat Array Vector dengan Range

# Membuat sebuah array vector  0 - 9
c = np.arange(10)
print(f'c : {c}')
# Membuat sebuah array vector  1- 10
d = np.arange(1,11)
print(f'd : {d}')
# Membuat sebuah array vector  0- 10 genap
e = np.arange(0,11,2)
print(f'e : {e}')
# Membuat sebuah array vector  10-0
f = np.arange(10,0,-1)
print(f'f : {f}')

c : [0 1 2 3 4 5 6 7 8 9]
d : [ 1  2  3  4  5  6  7  8  9 10]
e : [ 0  2  4  6  8 10]
f : [10  9  8  7  6  5  4  3  2  1]


In [45]:
#LINSPACE
#Membuat panjang array yg ditentukan (angka ketiga dari syntax), dengan jarak antar nilai pada array adalah sama

# Dari 1 - 10, sebanyak 4 angka
g = np.linspace(1,10,4)
print(f'g : {g}')
# Dari 0 - 10, sebanyak 2 angka
h = np.linspace(0,10,2)
print(f'h : {h}')
# Dari 0 - 10, sebanyak 5 angka
i = np.linspace(0,10,5)
print(f'i : {i}')
# Dari 1 - 10, sebanyak 10 angka
j = np.linspace(1,10,10)
print(f'j : {j}')

g : [ 1.  4.  7. 10.]
h : [ 0. 10.]
i : [ 0.   2.5  5.   7.5 10. ]
j : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [48]:
#RANDOM INTEGER

# Random integer dari 1 - 10, sebanyak 1 data
randInt = np.random.randint(1, 11) #--> (1,11) adalah arange dari 1-10 & (1/default/tidak ditampilak) adalah banyak data int yg ingin ditampilkan
print(randInt)
# Random integer dari 1 - 10, sebanyak 7 data
randInt2  = np.random.randint(1,11,7) #--> (1,11) adalah arange dari 1-10 & (7) adalah banyak data int yg ingin ditampilkan
print(randInt2)

1
[ 1  6  7  7 10  2  9]


In [44]:
#SHAPE & RESHAPE

# shape digunakan untuk melihat  bentuk array
k = np.arange(1,7)
print(f'Array k : {k}')
print(f'shape k : {k.shape}')

print()

# reshape digunakan untuk mengubah bentu array
# reshape(2, 3) --> Mengubah bentuk menjadi 2 baris 3 kolom
k1 = k.reshape(2, 3)
print(f'rehape k(2,3) :\n {k1}')
# reshape(3, 2) --> Mengubah bentuk menjadi 3 baris 2 kolom
k2 = k.reshape(3, 2)
print(f'rehape k(3,2) :\n {k2}')
# reshape(3, 2) --> Mengubah bentuk 3 baris 2 kolom, menjadi 1 baris
k3 = k2.reshape(6)
print(f'reshape k(3,2) mejadi 1 baris kembali : {k3}')


Array k : [1 2 3 4 5 6]
shape k : (6,)

rehape k(2,3) :
 [[1 2 3]
 [4 5 6]]
rehape k(3,2) :
 [[1 2]
 [3 4]
 [5 6]]
reshape k(3,2) mejadi 1 baris kembali : [1 2 3 4 5 6]


In [56]:
#MAX() & MIN()

# Random dari 0 - 49, sebanyak 10 data
rndmArr = np.random.randint(0,50,10)
print(rndmArr)

maxInt = rndmArr.max()
print(f'nilai max dari random array : {maxInt}')
minInt = rndmArr.min()
print(f'nilai min dari random array : {minInt}')

[ 3  3 19 35  5 36 27 42 14 30]
nilai max dari random array : 42
nilai min dari random array : 3


In [81]:
#MAX & MIN pada Array 2-d / MATRICS

vctr = np.arange(1,26)
print(f'Vector :\n {vctr}')
#reshape vector menjadi matrics (5,5)
mtrx = vctr.reshape(5,5)
print(f'Matrics (5,5):\n {mtrx}')

#Mencari nilai MAX & MIN dari matrics
maxMtrx = mtrx.max()
print(f'Nilai Max dari Matrics (5,5) : {maxMtrx}')
minMtrx = mtrx.min()
print(f'Nilai Min dari Matrics (5,5) : {minMtrx}')
print()

#Mencari nilai MAX & MIN baris ke 2&5 pada matrics

#ambil baris yang ingin dicari nilai Max & Min nya
print('Matrics baris 2&5 :')
print(mtrx[1])
print(mtrx[-1])
print()
print(f'Nilai Max pada baris ke-2 : {mtrx[1].max()}')
print(f'Nilai Min pada baris ke-4 (baris terakhir) : {mtrx[-1].min()}')




Vector :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Matrics (5,5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Nilai Max dari Matrics (5,5) : 25
Nilai Min dari Matrics (5,5) : 1

Matrics baris 2&5 :
[ 6  7  8  9 10]
[21 22 23 24 25]

Nilai Max pada baris ke-2 : 10
Nilai Min pada baris ke-4 (baris terakhir) : 21
