In [3]:
import numpy as np

#Vector (array satu dimensi)
numbers = [1,2,3,4,5]
arrayNumbers = np.array(numbers)

print(numbers)
print(arrayNumbers)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
#Matrics (array dua dimensi)

numbers2 =  [[1,2,3],[4,5,6],[7,8,9]]
arrayNumbers2 = np.array(numbers2)
print(arrayNumbers2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


arange

In [5]:
#Membuat sebuha array 0-9

arrRange = np.arange(10) #sebenarnya adalah (0,10,1)
print(arrRange)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Membuat sebuha array 1-10

arrRange = np.arange(1,11) #sebenarnya adalah (1,11,1)
print(arrRange)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#Membuat sebuha array nilai genap 0-10

arrRange = np.arange(0,11,2)
print(arrRange)

[ 0  2  4  6  8 10]


In [8]:
#Membuat sebuha array nilai genap 10-0

arrRange = np.arange(10,0,-2)
print(arrRange)

[10  8  6  4  2]


linspace

In [9]:
#Membuat array panjang yg ditentukan dan jarak antar angkanya sama

#Dari 0-10, sebanyak 5 angka

arrLin = np.linspace(0,10,5)
print(arrLin)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
#Dari 1-10, sebanyak 10 angka

arrLin = np.linspace(1,10,10)
print(arrLin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [23]:
#Dari 1-10, sebanyak 5 angka

arrLin = np.linspace(1,10,5)
print(arrLin)

[ 1.    3.25  5.5   7.75 10.  ]


reshape

In [47]:
# shape digunakan untuk melihat  bentuk array
arrRange = np.arange(1,7)
print(arrRange)
print(arrRange.shape)

[1 2 3 4 5 6]
(6,)


In [49]:
# reshape digunakan untuk mengubah bentu array
# reshape(2, 3) --> Mengubah bentuk menjadi 2 baris 3 kolom
arrRange = arrRange.reshape(2, 3)
print(arrRange)

[[1 2 3]
 [4 5 6]]


In [51]:
# reshape 3 baris 2 kolom
arrRange = arrRange.reshape(3, 2)
print(arrRange)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
arrRange = arrRange.reshape(6)
print(arrRange)

[1 2 3 4 5 6]


max() & min()

In [41]:
# Random dari 0 - 49, sebanyak 10 data
arrInt = np.random.randint(0, 50, 10)
print(arrInt)

[24 15 21 33 19 32  8 14 30 30]


In [42]:
maxInt = arrInt.max()
minInt = arrInt.min()
print(maxInt)
print(minInt)

33
8


In [43]:
arrRange = np.arange(1,26)
arrRange = arrRange.reshape(5,5)
print(arrRange)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
print('Nilai Max :',arrRange.max())
print('Nilai Min :',arrRange.min())

Nilai Max : 25
Nilai Min : 1


In [45]:
print(arrRange)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [46]:
print(arrRange[1])
print(arrRange[-1])
print(f'Nilai max untuk baris kedua : {arrRange[1].max()}')
print(f'Nilai min untuk baris terakhir : {arrRange[1].min()}')

[ 6  7  8  9 10]
[21 22 23 24 25]
Nilai max untuk baris kedua : 10
Nilai min untuk baris terakhir : 6


INDEXING & SELECTION

One Dimension

In [53]:
arrRange = np.arange(0,11)
print(arrRange)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [54]:
arrRange[4]

4

In [55]:
# Select dari index 2 - 6
print(arrRange[2:7])

[2 3 4 5 6]


In [56]:
# Select dari index awal - 6
print(arrRange[:7])

[0 1 2 3 4 5 6]


In [57]:
# Select dari index 2 - selesai
print(arrRange[2:])

[ 2  3  4  5  6  7  8  9 10]


    Broadcast

In [58]:
arrRange[2:7] = 99
print(arrRange)

[ 0  1 99 99 99 99 99  7  8  9 10]


Two Dimension

In [59]:
arrMatrics = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arrMatrics)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [60]:
print(arrMatrics[1])

[20 25 30]


In [61]:
# Access value
print(arrMatrics[1][1])
# or
print(arrMatrics[1, 1])

25
25


In [62]:

print(arrMatrics[0:2])

[[ 5 10 15]
 [20 25 30]]


In [63]:
print(arrMatrics)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [64]:
# row : 2 (index 0 - 1)
# column 1: (index 1 - terakhir)
arrMatrics[: 2, 1 :]

array([[10, 15],
       [25, 30]])

In [66]:
arrMatrics[1:, 0 :2]

array([[20, 25],
       [35, 40]])